---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
  user: treydock
  secure: "UcVpDmd35bucPPpFv2px+gHKxs4CiDzujdl+90dH2uGFsH8R8xRVp2EvL5C9SMZwNeAbgtbgbQ/Wr1S/ttDQdErdvd+4pZajZXi1HAbPT8AOk0ppxlMPFv4lfMey9LB76Mq/l83AtftUvj7etAGn4TQ/be/gZFfFE9QsBP/FOkU="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
